### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ethanryan** [y-js/y-websockets-server#12]
Using y-websockets-server and y-websockets-client in a React app.

When running React app, it compiles with warnings:

```
Compiled with warnings.

./node_modules/yjs/src/y.js
74:10-29 Critical dependency: the request of a dependency is an expression
```

Line 74 of ./node_modules/yjs/src/y.js:

`require(modulename)(Y)`

**Comment by aizatto** [comment]
Hi @ethanryan I ran into the same problem, did you ever solve this? Thanks in advance

**Comment by aizatto** [comment]
My temporary work around:

Open `node_modules/yjs/src/y.js` and disable line `74` and then restart your create-react-app

The offending line should look like

```js
// require(modulename)(Y)
```

**Comment by dmonad** [comment]
Interesting. Apparantly create-react-app defines `require` globally so the Yjs build expects that `require` is available (but it is really not).

Sorry, at this time I can't fix this anymore. v12 is frozen and I can't rework the module system anymore (because it would probably break other peoples work). This issue won't happen in v13.

Thanks for sharing your solution @aizatto !

**Comment by sarahm7** [comment]
@dmonad whats your timeline for the v13? is it going to be released this quarter perhaps?
