### ISSUE TITLE
Modifiable Socket Events

### ISSUE THREAD

**Issue by Joeao** [y-js/y-websockets-server#2]
It would be useful to have access to the joinRoom, yjsEvent and disconnect events on both server and client.
By intercepting data being sent to the client and adding your own from the server, you'd be able to leave the following y-richtext issues up to QuillJS & websockets. [#8](https://github.com/y-js/y-richtext/issues/8), [#85](https://github.com/y-js/y-richtext/issues/85), [#87](https://github.com/y-js/y-richtext/issues/87), [#88](https://github.com/y-js/y-richtext/issues/88) and [#99](https://github.com/y-js/y-richtext/issues/99).
Should also help out with issue [#95](https://github.com/y-js/y-richtext/issues/95).

**Comment by Joeao** [comment]
Another little thought on how this could be really useful is that it will give us access to the events to carry out the following:
1. When user leaves room resulting in the room being empty: Store memory data for this room into database and wipe memory data for this room.
2. When a user joins an empty room: Get data from database and place into memory.
3. When user joins a populated room: Get data from memory (as we currently do).

This would mean that we'd need functionality to get and destroy data from memory. But it may remove the need for you having to write various database adaptors.

It would make getting the data for the first user slower, but it's better than storing data in memory that isn't being accessed.

An addition to this process would also be great for storing version history in the database. (On 5 minute intervals, for example).

I've made some assumptions here and oversimplified things, so it's possible that this suggestion either veers away from your goals for YJS or is just plain dumb. In either case, I apologise.

**Comment by dmonad** [comment]
As I mentioned in y-js/y-richtext#87 You can listen to joinRoom and disconnect events easily. But I really don't want you to access the _yjsEvent_, because it is very likely that I will change them in the following month. You should rather listen to the high level events, unless you have a really good reason.

The approach you describe is very nicely describes how I planned  to store data in yjs@0.5 (when we just had in-memory storage). The cool thing about the database-storage is, that you can just plug-in redis, for instance, and make one small database request for every change a user makes. Your approach suggests to store all the data in a regular basis. That's feasible, I guess, but it's more desirable to work directly on the database - then you don't have to store any yjs data in-memory at all. It's all persistently stored in a database.

Another advantage of the database adapters is that you can support offline editing for the clients (indexeddb is already supported). Since there is no way to store all data before a user closes the window, database adapters are really the only solution.

Finally I want to say that creating a database adapter is fairly easy. I just haven't decided which db is the best choice for server (and there are more important things right now).

## 

Your first comment suggests to leave some issues to QuillJs & websockets. You should be able to switch from one connector to another without bigger issues, and/or loss of features. Features should not be connector-specific.

If you really really want to intercept yjsEvents. You can proxy y.connector.receiveMessage (against my  advice ;-) )
